/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.dontesta.labs.liferay.lrbo16.servicebuilder.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Horse service. Represents a row in the &quot;LRBO_HORSE_Horse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.dontesta.labs.liferay.lrbo16.servicebuilder.model.impl.HorseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.dontesta.labs.liferay.lrbo16.servicebuilder.model.impl.HorseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Horse
 * @see it.dontesta.labs.liferay.lrbo16.servicebuilder.model.impl.HorseImpl
 * @see it.dontesta.labs.liferay.lrbo16.servicebuilder.model.impl.HorseModelImpl
 * @generated
 */
@ProviderType
public interface HorseModel extends BaseModel<Horse>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a horse model instance should use the {@link Horse} interface instead.
	 */

	/**
	 * Returns the primary key of this horse.
	 *
	 * @return the primary key of this horse
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this horse.
	 *
	 * @param primaryKey the primary key of this horse
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this horse.
	 *
	 * @return the uuid of this horse
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this horse.
	 *
	 * @param uuid the uuid of this horse
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the horse ID of this horse.
	 *
	 * @return the horse ID of this horse
	 */
	public long getHorseId();

	/**
	 * Sets the horse ID of this horse.
	 *
	 * @param horseId the horse ID of this horse
	 */
	public void setHorseId(long horseId);

	/**
	 * Returns the group ID of this horse.
	 *
	 * @return the group ID of this horse
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this horse.
	 *
	 * @param groupId the group ID of this horse
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this horse.
	 *
	 * @return the company ID of this horse
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this horse.
	 *
	 * @param companyId the company ID of this horse
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this horse.
	 *
	 * @return the user ID of this horse
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this horse.
	 *
	 * @param userId the user ID of this horse
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this horse.
	 *
	 * @return the user uuid of this horse
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this horse.
	 *
	 * @param userUuid the user uuid of this horse
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this horse.
	 *
	 * @return the user name of this horse
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this horse.
	 *
	 * @param userName the user name of this horse
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this horse.
	 *
	 * @return the create date of this horse
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this horse.
	 *
	 * @param createDate the create date of this horse
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this horse.
	 *
	 * @return the modified date of this horse
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this horse.
	 *
	 * @param modifiedDate the modified date of this horse
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this horse.
	 *
	 * @return the name of this horse
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this horse.
	 *
	 * @param name the name of this horse
	 */
	public void setName(String name);

	/**
	 * Returns the age of this horse.
	 *
	 * @return the age of this horse
	 */
	public int getAge();

	/**
	 * Sets the age of this horse.
	 *
	 * @param age the age of this horse
	 */
	public void setAge(int age);

	/**
	 * Returns the gender of this horse.
	 *
	 * @return the gender of this horse
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this horse.
	 *
	 * @param gender the gender of this horse
	 */
	public void setGender(String gender);

	/**
	 * Returns the kind of this horse.
	 *
	 * @return the kind of this horse
	 */
	@AutoEscape
	public String getKind();

	/**
	 * Sets the kind of this horse.
	 *
	 * @param kind the kind of this horse
	 */
	public void setKind(String kind);

	/**
	 * Returns the mantle of this horse.
	 *
	 * @return the mantle of this horse
	 */
	@AutoEscape
	public String getMantle();

	/**
	 * Sets the mantle of this horse.
	 *
	 * @param mantle the mantle of this horse
	 */
	public void setMantle(String mantle);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse horse);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse> toCacheModel();

	@Override
	public it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse toEscapedModel();

	@Override
	public it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}