/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.dontesta.labs.liferay.lrbo16.servicebuilder.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse;
import it.dontesta.labs.liferay.lrbo16.servicebuilder.model.HorseModel;
import it.dontesta.labs.liferay.lrbo16.servicebuilder.model.HorseSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Horse service. Represents a row in the &quot;LRBO_HORSE_Horse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link HorseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HorseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HorseImpl
 * @see Horse
 * @see HorseModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class HorseModelImpl extends BaseModelImpl<Horse> implements HorseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a horse model instance should use the {@link Horse} interface instead.
	 */
	public static final String TABLE_NAME = "LRBO_HORSE_Horse";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "horseId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "age", Types.INTEGER },
			{ "gender", Types.VARCHAR },
			{ "kind", Types.VARCHAR },
			{ "mantle", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("horseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("age", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("gender", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kind", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mantle", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table LRBO_HORSE_Horse (uuid_ VARCHAR(75) null,horseId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,age INTEGER,gender VARCHAR(75) null,kind VARCHAR(75) null,mantle VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table LRBO_HORSE_Horse";
	public static final String ORDER_BY_JPQL = " ORDER BY horse.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LRBO_HORSE_Horse.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(it.dontesta.labs.liferay.lrbo16.servicebuilder.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(it.dontesta.labs.liferay.lrbo16.servicebuilder.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(it.dontesta.labs.liferay.lrbo16.servicebuilder.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long NAME_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Horse toModel(HorseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Horse model = new HorseImpl();

		model.setUuid(soapModel.getUuid());
		model.setHorseId(soapModel.getHorseId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setAge(soapModel.getAge());
		model.setGender(soapModel.getGender());
		model.setKind(soapModel.getKind());
		model.setMantle(soapModel.getMantle());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Horse> toModels(HorseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Horse> models = new ArrayList<Horse>(soapModels.length);

		for (HorseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(it.dontesta.labs.liferay.lrbo16.servicebuilder.service.util.PropsUtil.get(
				"lock.expiration.time.it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse"));

	public HorseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _horseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHorseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _horseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Horse.class;
	}

	@Override
	public String getModelClassName() {
		return Horse.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("horseId", getHorseId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("age", getAge());
		attributes.put("gender", getGender());
		attributes.put("kind", getKind());
		attributes.put("mantle", getMantle());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long horseId = (Long)attributes.get("horseId");

		if (horseId != null) {
			setHorseId(horseId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Integer age = (Integer)attributes.get("age");

		if (age != null) {
			setAge(age);
		}

		String gender = (String)attributes.get("gender");

		if (gender != null) {
			setGender(gender);
		}

		String kind = (String)attributes.get("kind");

		if (kind != null) {
			setKind(kind);
		}

		String mantle = (String)attributes.get("mantle");

		if (mantle != null) {
			setMantle(mantle);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getHorseId() {
		return _horseId;
	}

	@Override
	public void setHorseId(long horseId) {
		_horseId = horseId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public int getAge() {
		return _age;
	}

	@Override
	public void setAge(int age) {
		_age = age;
	}

	@JSON
	@Override
	public String getGender() {
		if (_gender == null) {
			return StringPool.BLANK;
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		_gender = gender;
	}

	@JSON
	@Override
	public String getKind() {
		if (_kind == null) {
			return StringPool.BLANK;
		}
		else {
			return _kind;
		}
	}

	@Override
	public void setKind(String kind) {
		_kind = kind;
	}

	@JSON
	@Override
	public String getMantle() {
		if (_mantle == null) {
			return StringPool.BLANK;
		}
		else {
			return _mantle;
		}
	}

	@Override
	public void setMantle(String mantle) {
		_mantle = mantle;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Horse.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Horse.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Horse toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Horse)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HorseImpl horseImpl = new HorseImpl();

		horseImpl.setUuid(getUuid());
		horseImpl.setHorseId(getHorseId());
		horseImpl.setGroupId(getGroupId());
		horseImpl.setCompanyId(getCompanyId());
		horseImpl.setUserId(getUserId());
		horseImpl.setUserName(getUserName());
		horseImpl.setCreateDate(getCreateDate());
		horseImpl.setModifiedDate(getModifiedDate());
		horseImpl.setName(getName());
		horseImpl.setAge(getAge());
		horseImpl.setGender(getGender());
		horseImpl.setKind(getKind());
		horseImpl.setMantle(getMantle());

		horseImpl.resetOriginalValues();

		return horseImpl;
	}

	@Override
	public int compareTo(Horse horse) {
		int value = 0;

		value = getName().compareTo(horse.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Horse)) {
			return false;
		}

		Horse horse = (Horse)obj;

		long primaryKey = horse.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		HorseModelImpl horseModelImpl = this;

		horseModelImpl._originalUuid = horseModelImpl._uuid;

		horseModelImpl._originalGroupId = horseModelImpl._groupId;

		horseModelImpl._setOriginalGroupId = false;

		horseModelImpl._originalCompanyId = horseModelImpl._companyId;

		horseModelImpl._setOriginalCompanyId = false;

		horseModelImpl._setModifiedDate = false;

		horseModelImpl._originalName = horseModelImpl._name;

		horseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Horse> toCacheModel() {
		HorseCacheModel horseCacheModel = new HorseCacheModel();

		horseCacheModel.uuid = getUuid();

		String uuid = horseCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			horseCacheModel.uuid = null;
		}

		horseCacheModel.horseId = getHorseId();

		horseCacheModel.groupId = getGroupId();

		horseCacheModel.companyId = getCompanyId();

		horseCacheModel.userId = getUserId();

		horseCacheModel.userName = getUserName();

		String userName = horseCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			horseCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			horseCacheModel.createDate = createDate.getTime();
		}
		else {
			horseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			horseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			horseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		horseCacheModel.name = getName();

		String name = horseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			horseCacheModel.name = null;
		}

		horseCacheModel.age = getAge();

		horseCacheModel.gender = getGender();

		String gender = horseCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			horseCacheModel.gender = null;
		}

		horseCacheModel.kind = getKind();

		String kind = horseCacheModel.kind;

		if ((kind != null) && (kind.length() == 0)) {
			horseCacheModel.kind = null;
		}

		horseCacheModel.mantle = getMantle();

		String mantle = horseCacheModel.mantle;

		if ((mantle != null) && (mantle.length() == 0)) {
			horseCacheModel.mantle = null;
		}

		return horseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", horseId=");
		sb.append(getHorseId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", age=");
		sb.append(getAge());
		sb.append(", gender=");
		sb.append(getGender());
		sb.append(", kind=");
		sb.append(getKind());
		sb.append(", mantle=");
		sb.append(getMantle());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("it.dontesta.labs.liferay.lrbo16.servicebuilder.model.Horse");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>horseId</column-name><column-value><![CDATA[");
		sb.append(getHorseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>age</column-name><column-value><![CDATA[");
		sb.append(getAge());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gender</column-name><column-value><![CDATA[");
		sb.append(getGender());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kind</column-name><column-value><![CDATA[");
		sb.append(getKind());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mantle</column-name><column-value><![CDATA[");
		sb.append(getMantle());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Horse.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Horse.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _horseId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private int _age;
	private String _gender;
	private String _kind;
	private String _mantle;
	private long _columnBitmask;
	private Horse _escapedModel;
}