
package com.predic8.wsdl.crm.crmservice._1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.predic8.crm._1.CustomerType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRMServicePT", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/")
@XmlSeeAlso({
    com.predic8.common._1.ObjectFactory.class,
    com.predic8.crm._1.ObjectFactory.class,
    com.predic8.wsdl.crm.crmservice._1.ObjectFactory.class
})
public interface CRMServicePT {


    /**
     * 
     * @param customer
     */
    @WebMethod(action = "create_action")
    @RequestWrapper(localName = "create", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "com.predic8.wsdl.crm.crmservice._1.CreateType")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "com.predic8.wsdl.crm.crmservice._1.CreateResponse")
    public void create(
        @WebParam(name = "customer", targetNamespace = "")
        CustomerType customer);

    /**
     * 
     * @param id
     * @return
     *     returns com.predic8.crm._1.CustomerType
     */
    @WebMethod(action = "get_action")
    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "com.predic8.wsdl.crm.crmservice._1.GetType")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "com.predic8.wsdl.crm.crmservice._1.GetResponseType")
    public CustomerType get(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @return
     *     returns java.util.List<com.predic8.crm._1.CustomerType>
     */
    @WebMethod(action = "getAll_action")
    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "com.predic8.wsdl.crm.crmservice._1.GetAllType")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://predic8.com/wsdl/crm/CRMService/1/", className = "com.predic8.wsdl.crm.crmservice._1.GetAllResponseType")
    public List<CustomerType> getAll();

}
